Fixing incompatibility issue with LAMMPS-2Aug2023
uf3/uf3 pull request #103
Opened 2023-11-24 01:28 UTC by monk-04

Fixes #101 and #102

2023-11-24 06:33 UTC, henk789 approved these changes
LGTM

2023-11-27 13:57 UTC, JasonGibsonUfl requested changes
I have tested the new implementation on LAMMPS-2023 and the new implementation runs correctly. However, I am concerned about the new input format for the 3-Body terms. Mainly my concern is that it is not intuitive to have two numerical definitions that are ignored prior to the actual definition. I see in the README that this is necessary to address changes in the LAMMPS core code. @monk-04 Can we hide this from the end user? If not, can you explain why the two ignored variables must be user-defined?

2023-11-27 13:57 UTC, JasonGibsonUfl commented on lammps_plugin/README.rst
> +   pair_coeff 1 1 1 1 1 A_A_A
This is a confusing way to define the 3-Body inputs. If we progress with this format of the first two numbers being ignored I suggest changing the README to the following convention:

```
pair_coeff * * 1 1 1 A_A_A
pair_coeff * * 1 1 2 A_A_B
```

2023-11-27 13:57 UTC, JasonGibsonUfl commented on lammps_plugin/README.rst
> +   pair_coeff 1 1 1 1 1 A_A_A
In this format, it is easier to read the interactions being defined

2023-11-27 15:27 UTC, monk-04 commented
@JasonGibsonUfl  Answer to both of your questions is that the lammps core code reads the input file.

As soon as it encounters a 'pair_coeff' line it reads the first two arguments to pair_coeff and sorts them if they are numeric values. These sorted vales are then passed to UF3 Lammps. We have no control on it.


Another solution to this issue is imposing  restriction on the user to always provide UF3 Lammps pot files in ascending order.

For example, instead of -
`pair_coeff   2 1 1 A_B_B` where A is 2 and B is 1 in the structure
provide-
`pair_coeff   1 2 2 A_B_B` and change A to 1 and B to 2.

We will have to explicitly mention in our README that only the above triplets (ie ascending order) are valid.


Regarding, `pair_coeff * * 1 2 2 A_B_B` the current implementation in the pull request should work for this format though I have not tested it. 
But then again `*` character means something special for Lammps users and this particular format might be equally unintuitive as the other.

2023-11-27 16:31 UTC, henk789 commented
> For example, instead of -
pair_coeff   2 1 1 A_B_B where A is 2 and B is 1 in the structure
provide-
pair_coeff   1 2 2 A_B_B and change A to 1 and B to 2.

In that case, users couldn't specify both `A_B_B` and `B_A_A` because one would have to be `2 1 1`, or am I missing something?

I agree that `* * i j k` looks less confusing than `1 1`. It should, however, also be possible to make them more arbitrary such that they don't match exising LAMMPS syntax, such as `pair_coeff 3 b i j k`. That would also give an intuitive meaning to what interaction is specified. What could also work is `pair_coeff 3b i j k` because even with reordering, the code could identify the `2b` or `3b`. I'm not sure how that behaves with type labels, though, because I believe they are mapped to integers before `coeff` receives them.

2023-11-27 16:53 UTC, monk-04 commented
@henk789 You are correct. I completely forgot about the other interaction.

2023-11-27 19:20 UTC, monk-04 commented
@henk789 I like your suggestion.

2023-11-27 19:31 UTC, JasonGibsonUfl approved these changes
@monk-04 The updated version runs properly and is in an intuitive format. Great work!

2023-11-27 19:31 UTC, merged