Added drop_columns feature; usefull for optimizing cutoffs
uf3/uf3 pull request #86
Opened 2023-09-24 18:51 UTC by monk-04

If an HDF5 file with larger radial cutoffs and uniform knot spacing exists, it is possible to fit a model with smaller cutoffs without regenerating the HDF5 file. This feature can be used for optimizing the radial cutoffs.

This push implements the above feature.

util/optimize.py provides some useful functions for getting the appropriate columns. These columns correspond to the columns of the HDF5 file (created using larger cutoffs), which should be ignored while fitting the model to lower cutoffs.

'least_squares.WeightedLinearModel.fit_from_file' and 'least_squares.WeightedLinearModel.batched_predict' accepts new argument 'drop_columns'. Providing a list of columns to this argument results in ignoring those columns while fitting and predicting steps.

- [ ] Create an example for the W system demonstrating this feature

2023-09-25 13:42 UTC, JasonGibsonUfl requested changes
This is an exxcelent feature of UF3 that needs to be highlighted and easily accessible. However for it to be useful it needs to be functional for more than rmin != 0. Another point of concern is that this feature will not be apparent unless a user digs into the source code. An example notebook would benefit this feature. 

`list` in lines 365 and 490 should be `List[str]`.

The function `get_bspline_config` is too rigid and variables are defined in arbitrary locations. I worry this may lead to incorrect use. For example `trailing_trim` and `leading_trim` are defined seemingly in the middle of the functions. If for some reason a user featurizes using `trailing_trim =4` they would not know that this function does not work for the given configuration.

We need to be a bit selective in how verbose we are in method and variable names. For example: `def get_possible_lower_cutoffs(original_bspline_config):` can be reduced to `def get_cuttoffs(bspline_config)` or `def get_lower_cuttoffs(bspline_config)`

In line 158 `original_bspline_config` is stated to be `bspline_config` however this is an internal definition. `original_bspline_config` should be defined as  `bspline.BSplineBasis`

method description in line 154 should be `3-body` not `2-body`

Can you provide a more informative `ValueError` for lines 101-116. It is not clear what the failed internal check is

2023-09-25 15:22 UTC, monk-04 commented
I have a checklist in my first comment that talks about adding an example.

Regarding the comment about the code not working when rmin!=0, the code might work when rmin!=0, I just haven't tested it. We should probably keep the condition for now and later remove it when we have extensively tested it.

I will make the changes in line 365 and 490.

I can make get_bspline_config a bit more flexible like accepting different knot spacing for 2-body and 3-body term. Regarding the leading trim and trailing trim, as I said for rmin I haven't had the time to test other settings.

I will add extra checks in `get_columns_to_drop_2b` and `get_columns_to_drop_3b`, to check for trims, knot_spacing, and some other stuff.

@JasonGibsonUfl I like your suggestion for renaming the functions.

Suggestions for line 158 and 154 noted.

The `ValueError` for internal checks is redundant check. For the drop_columns feature to work the smaller cutoff needs to be a knot of the original knots with larger cutoffs.

2023-09-26 17:41 UTC, monk-04 commented
As per @JasonGibsonUfl suggestions, I have made `get_bspline_config` a bit more flexible. It now works when `rmin!=0`.

I added some extra checks to `get_columns_to_drop_2b` and `get_columns_to_drop_3b` functions.

Also added one more unit test (see `config_2` in `test_optimize.py`), which is failing with my current `get_columns_to_drop_3b` algorithm.

The algorithm only fails when the `modify_3b_cutoff` is either 4.5 or 6.3. It works for other values like for example 5.4, 7.2, 1.8, etc.

@JasonGibsonUfl @sxie22 any suggestions?

2023-09-28 19:57 UTC, monk-04 commented
The algorithm is only failing when `rmin_3b!=0`. When `rmin_3b=0`, it passes all the cases I was able to come up with.

2023-09-28 21:44 UTC, monk-04 commented
I think I have found the reason why my `drop_column` algorithm is failing. Refer to issue #89 for more details.

2023-10-10 13:38 UTC, JasonGibsonUfl reviewed
I like the changes made to this feature. My comments are mostly about styling. Most are reoccurring such as no white space after `,`.  I would suggest using `flake8` to catch these.

The other concern I have is in variable naming. For example, line 229 exceeds PEP8 line length convention by over 30 characters. This is because of the length of the variable `num_columns_to_drop_3b_double` this could be shortened to something like `n_drop_3b_long`. Additionally, abbreviations should be used consistently. In line 237 index is abbreviated to `ind` but in the proceeding line it is not abbreviated.

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +            raise ValueError("Provided rmax_2b does not conatin integer number of \n\
This line is line seems to be over-indented.

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +            raise ValueError("Provided rmax_3b does not conatin integer number of \n\
This one as well.

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +    if leading_trim!=0:
missing whitespace around operator

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +    if trailing_trim!=3:
missing whitespace around operator

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +    if not(np.isclose((rmax_3b_double%knot_spacing_3b),0) or \
missing whitespace around modulo operator

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +    r_min_map.update({i:[rmin_3b,rmin_3b,rmin_3b] for i in chemical_system.interactions_map[3]})
missing whitespace after ','

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +        if rmax_2b_poss[i] not in  original_bspline_config.knots_map[interaction_2b]:
Extra white space after `in`

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +    return {"rmax_2b_poss":rmax_2b_poss, "rmax_3b_poss":rmax_3b_poss}
missing whitespace after ':'

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +    if original_bspline_config.leading_trim!=0:
missing whitespace around operator

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +        if not modify_3b_cutoff in original_bspline_config.knots_map[interaction][0]:
This is an unconventional use of the `not` operator. typically the syntax is `not in`

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +        columns_to_keep_index_3b = np.where(np.isin(column_names[start_ind_3b:end_ind_3b],columns_to_keep))[0]
This variable is not used.

2023-10-10 13:38 UTC, JasonGibsonUfl commented on uf3/regression/optimize.py
> +def get_possible_lower_cutoffs(original_bspline_config):
I do not like this function name. I suggest removing `possible` as it makes the function's use confusing.

2023-10-11 16:10 UTC, monk-04 commented
Formated the files according to @JasonGibsonUfl suggestions and also added an example jupyter notebook

2023-11-17 16:48 UTC, sxie22 approved these changes

2023-11-20 19:56 UTC, monk-04 commented
Merging!

2023-11-20 19:56 UTC, merged